import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Header from "./components/Header";

const Home = () => {
  

  return (
    <div className="w-[70%] flex flex-col m-auto">
      <Head>
        <title>A-Team Brewery App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

    </div>
  );
};

export default Home;
