import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

const Home = () => {
  

  return (
    <div>
      <Head>
        <title>A-Team Brewery App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  );
};

export default Home;
